#%%
from typing import Any, List, Dict, Union, Optional
import yaml
import os
import pandas as pd
from datetime import datetime
from tqdm import tqdm
from asteval import Interpreter
import argparse

from general_utils import read_data_frame, save_data_frame, get_logger

logger = get_logger(__name__)

EMPTY_VALUE = "Empty"

ORIG_ID_PREFIX = "__"

# All columns that should be in the ID code generation config file
class IDCodeColumns:
    CLASS = "class"
    SLOT = "slot"
    CODE = "code"

# Keys for linkage paths. These are used in the config file under the "class_linkages" key.
class LinkageKeys:
    SOURCE_CLASS = "source_class"
    SOURCE_SLOT = "source_slot"
    TARGET_CLASS = "target_class"
    TARGET_SLOT = "target_slot"

class FunctionBindings:
    """All functions/properties accessible from ID code using the global fn object (eg. fn.makeid("a", "b", "c")).
    """
    def __init__(self, generator: "IDGenerator"):
        self.generator = generator
    
    @property
    def rownum(self) -> str:
        return "{:03d}".format(self.generator.current_row_index)
    
    @property
    def emptystring(self) -> str:
        return EMPTY_VALUE
    
    def makeid(self, *args) -> str:
        firstcap = False
        if not args:
            return None
        args = [str(v) for v in args]
        args = [v for v in args if len(v)]
        args = ["%s%s" % (v[0].upper() if (idx or firstcap) else v[0].lower(), v[1:]) for idx, v in enumerate(args)]
        v = "".join(args)
        v = v.replace(" ", "")
        return v
        
    def date(self, d):
        return d

    def countrows(self, cls: str, slot: str, equals) -> int:
        return len(self.generator.get_rows_equal(cls, slot, equals))

class DataBindings():
    """All data bindings accessible from ID generation code through the dat object (eg. dat.samples.sampleID).
    """
    def __init__(self, generator: "IDGenerator", root_class: Optional[str], sub_class_names: Optional[List[str]]):
        """Constructor for DataBindings.

        Args:
            generator (IDGenerator): The ID Generator that the bindings are for.
            root_class (Optional[str]): The name of the class that this binding is for. A class name is a table name.
                If this is set then this binding represents a single table, and we retrieve an attribute on the
                binding to get values within a column of the table. If root_class is None then it is the top-level
                binding that contains all the classes (ie. tables). In this case, sub_class_names must be set to
                a list of all the recognized tables, and to retrieve any of these tables we retrieve an attribute
                on the binding to get the binding for the table (which we can in turn retrieve columns from). For
                example, bindingsObj.table. Since a new binding is returned when accessing this attribute, we can
                use the returned binding to then retrieve columns of the class, eg. bindingsObj.table.column. The
                actual row that is retrieved depends on the current_row_index of the generator.
            sub_class_names (Optional[List[str]]): If root_class is None, then sub_class_names must be set to a list
                of all the recognized classes (ie. tables). To retrieve the bindings for one of these classes, we
                would retrieve the attribute (using the name of the class) on this binding. For example,
                bindingsObj.column. The actual row that is retrieved depends on the current_row_index of the generator.
        """
        self.generator = generator
        self.root_class = root_class
        if sub_class_names:
            self.sub_classes = {
                cls: DataBindings(generator, root_class=cls, sub_class_names=[]) for cls in sub_class_names
            }
        else:
            self.sub_classes = None
    
    def __getattr__(self, name):
        if self.sub_classes:
            return self.sub_classes[name]
        # source_class and source_index are the current class and row being generated by the generator.
        # self.root_class and name are the class and slot that we want to get the value of. The row
        # we retrieve the value from depends on which rows in self.root_class are linked to the row
        # in source_class at index source_index.
        source_class = self.generator.current_class
        source_index = self.generator.current_row_index
        v = self.generator.get_first_linked_value(source_class, source_index, self.root_class, name)
        return self.generator.finalize_value(v)

class IDGenerator(object):
    def __init__(self, data_dir: str, config_file: str, id_code_file: str, id_code_sheet: str = None):
        """Constructor for IDGenerator.

        Args:
            data_dir (str): Directory containing all data files to load. The file names (without extension) should
                be the name of the class for the file. These can be CSV, TSV, TXT, YAML, or YML files.
            config_file (str): The configuration file.
            id_code_file (str): The tabular file containing the ID generation code for each class/slot that represents
                an ID to be generated. Can be an XLSX, CSV, TSV, TXT, YAML, or YML file. If an Excel file then
                id_code_sheet should also be set.
            id_code_sheet (str, optional): If id_code_file is an Excel file, then the sheet name to load that contains
                the ID generation code. Defaults to None.
        """
        # Load all data from disk
        self.data = {}        
        for f in os.listdir(data_dir):
            class_name, ext = os.path.splitext(f)
            # if class_name not in ["sites"]:
            #     continue
            if ext in [".csv", ".tsv", ".txt", ".yaml", ".yml"]:
                logger.info(f"Loading data from {f}")
                self.data[class_name] = read_data_frame(os.path.join(data_dir, f))

        # Prepare the code for calculating IDs
        self.prepare_id_code(id_code_file, id_code_sheet)

        # Prepare the IDs in the loaded DataFrames based on the config
        self.prepare_ids()

        # Prepare the config file
        self.prepare_config(config_file)

        # Create the bindings and interpreter
        all_classes = list(self.config["class_linkages"].keys())
        all_classes += [cls for lnk in self.config["class_linkages"].values() for cls in lnk.keys()]
        self.bindings = {
            "dat" : DataBindings(self, root_class="", sub_class_names=all_classes),
            "fn" : FunctionBindings(self),
        }
        self.interpreter = Interpreter(usersyms=self.bindings)
        
    def is_id_generated_slot(self, cls: str, slot: str) -> bool:
        """Determine if the slot in the class is for an ID that gets generated.

        Args:
            cls (str): The class of the slot.
            slot (str): The slot.

        Returns:
            bool: True if the slot gets its ID generated, False if it doesn't.
        """
        return slot in self.class_ids[cls]
        
    def prepare_config(self, config: str):
        """Load and prepare the configuration file for the ID generator.

        Args:
            config (str): Path to the configuration file.

        Raises:
            ValueError: There is an error in the configuration file.
        """
        with open(config, "r") as f:
            self.config = yaml.safe_load(f)
            
        def make_orig(cls: str, slot: str) -> str:
            if self.is_id_generated_slot(cls, slot):
                return f"{ORIG_ID_PREFIX}{slot}"
            return slot
        
        # Clean up class_linkages by adding any missing values, and replacing generated ID slots with the slot name
        # with two preceding underlines.
        for source_class, target_linkages in self.config["class_linkages"].items():
            for target_class, linkages in target_linkages.items():
                if not isinstance(linkages, list):
                    linkages = [linkages]
                prev_class = source_class
                for idx, linkage in enumerate(linkages):
                    # Add SOURCE_CLASS and TARGET_CLASS if they aren't set
                    if LinkageKeys.SOURCE_CLASS not in linkage:
                        linkage[LinkageKeys.SOURCE_CLASS] = prev_class
                    if LinkageKeys.TARGET_CLASS not in linkage:
                        if idx < len(linkages) - 1:
                            raise ValueError(f"Error in configuration for class linkages, from class '{source_class}' to class '{target_class}': A target_class must be specified for all but the last linkage in the linkage steps.")
                        linkage[LinkageKeys.TARGET_CLASS] = target_class
                    
                    # Rename the SOURCE_SLOT and TARGET_SLOT so that they point to the columns where the original
                    # IDs are contained. These original slots will remain unchanged. For example, we rename the
                    # slot datasetID to {ORIG_ID_PREFIX}datasetID. datasetID will contain the newly calculated ID 
                    # whereas {ORIG_ID_PREFIX}datasetID will always contain the original unmodified ID.
                    linkage[LinkageKeys.SOURCE_SLOT] = make_orig(source_class, linkage[LinkageKeys.SOURCE_SLOT])
                    linkage[LinkageKeys.TARGET_SLOT] = make_orig(target_class, linkage[LinkageKeys.TARGET_SLOT])
                        
                    prev_class = linkage[LinkageKeys.TARGET_CLASS]
        
    def prepare_id_code(self, id_code_file: str, id_code_sheet: Optional[str] = None):
        """Load and prepare the ID generation code from the specified file. The file should contain all the
        columns found in IDCodeColumns.

        Args:
            id_code_file (str): The XLSX, CSV, TSV, YAML, YML, or TXT file containing the ID generation code. If an Excel file we
                load the sheet named id_code_sheet.
            id_code_sheet (Optional[str], Optional): If id_code_file is an Excel file, then this is the sheet name to load.
        """
        if os.path.splitext(id_code_file)[1].lower() == ".xlsx":
            id_code_df = pd.read_excel(id_code_file, id_code_sheet if id_code_sheet else 0)
        else:
            id_code_df = read_data_frame(id_code_file)
        id_code_df = id_code_df.dropna(subset=[IDCodeColumns.CLASS, IDCodeColumns.SLOT, IDCodeColumns.CODE], axis=0, how="any")
        self.id_code_df = id_code_df
        
        # Determine all the ID slots that need to be calculated (in all classes).
        self.class_ids = {}
        for _, row in self.id_code_df.iterrows():
            cls = row[IDCodeColumns.CLASS]
            slot = row[IDCodeColumns.SLOT]
            if cls not in self.class_ids:
                self.class_ids[cls] = []
            if slot not in self.class_ids[cls]:
                self.class_ids[cls].append(slot)
        
    def prepare_ids(self):
        """Do some preparation of the ID columns in the loaded DataFrames.
        
        We will copy the IDs to new columns where the names are preceded by two underscores. The values
        in the new columns will remain unchanged, but the values in the old columns will be set to None and
        their IDs generated once make_all_ids is called.
        """
        self.current_class = None
        self.current_row_index =  None
        
        for cls, df in self.data.items():
            if cls not in self.class_ids:
                continue
            logger.info(f"Preparing IDs for class '{cls}'")
            # Copy all ID columns to new columns preceded by ORIG_ID_PREFIX (eg. __), and clear the
            # original column. Once make_all_ids is called, if the original column has a None value
            # then that means we need to calculate the ID for that column (while the double-underscore
            # column remains unchanged).
            slots = self.class_ids[cls]
            slots = [s for s in slots if s in df.columns]
            if len(slots) == 0:
                continue
            orig_values_slots = [f"{ORIG_ID_PREFIX}{s}" for s in slots]
            df[orig_values_slots] = df[slots]
            df[slots] = None
            
    def get_code(self, cls: str, slot: str) -> Optional[str]:
        """Get the ID code for generating the ID for the specified slot.

        Args:
            cls (str): The class the slot belongs to.
            slot (str): The slot to get the code for.

        Raises:
            ValueError: No code is available for the specified slot.

        Returns:
            str: The code that generates the ID for the slot. None if no code is available.
        """
        code = self.id_code_df[(self.id_code_df[IDCodeColumns.CLASS] == cls) & (self.id_code_df[IDCodeColumns.SLOT] == slot)]
        if len(code) == 0:
            # raise ValueError(f"No code found for class '{cls}' and slot '{slot}'")
            return None
        code = code[IDCodeColumns.CODE].iloc[0]
        return code
               
    def make_all_ids(self):
        """Generate all IDs in all DataFrames, according to the ID generation code and the config file.

        Raises:
            ValueError: ID generation code was found for a class and slot that does not exist in the class's
                loaded DataFrame.
        """
        logger.info(f"Making all IDs...")
        tic = datetime.now()
        all_classes = self.data.keys()
        for idx, cls in enumerate(all_classes):
            logger.info(f"Making IDs for class '{cls}' ({idx+1}/{len(all_classes)})")
            all_slots = self.class_ids.get(cls, [])
            for idx in tqdm(self.data[cls].index):
                for slot in all_slots:
                    if slot not in self.data[cls]:
                        raise ValueError(f"Found slot '{slot}' in class '{cls}' in ID code file that does not exist in the source data.")
                    v = self.data[cls][slot].loc[idx]
                    if not pd.isna(v):
                        continue
                    self.current_class = cls
                    self.current_row_index = idx
                    self.calculate_id(cls, slot, idx)
        logger.info(f"Finished making all IDs: {datetime.now() - tic}")

    def get_first_linked_row(self, source_class: str, source_index: int, target_class: str, linkage_path: Optional[Union[Dict, List[Dict]]]=None) -> pd.Series:
        """Get the first row in target_class that is linked to the row at index source_index in the class source_class.

        Args:
            source_class (str): The source class.
            source_index (int): The row index in the source class that we want to get the linked rows for.
            target_class (str): The target class to get the linked rows from.
            linkage_path (Optional[Union[Dict, List[Dict]]], Optional): The configuration specifying how to link from source_class to target_class. If None
                then the default linkage path from source_class to target_class in the config file is used. Defaults to None.

        Returns:
            pd.Series: The first linked row in target_class, or None if there are no linked rows.
        """
        rows = self.get_linked_rows(source_class, source_index, target_class, linkage_path)
        if rows is None or len(rows) == 0:
            return None
        return rows.iloc[0]
                    
    def get_first_linked_value(self, source_class: str, source_index: int, target_class: str, target_slot: str, linkage_path: Optional[Union[Dict, List[Dict]]]=None) -> Any:
        """Get the first value in target_class and slot target_slot that is linked to the row in source_class at row index source_index, using
        the linkage_path to determine how to link from source_class to target_class. If linkage_path is None then we use the
        linkage path found in the config file (self.config["class_linkages"])

        Args:
            source_class (str): The source class we are linking from.
            source_index (int): The row index in the source class to link from.
            target_class (str): The target class that we want to get the linked value from.
            target_slot (str): The slot in the target class to get the value from.
            linkage_path (Optional[Union[Dict, List[Dict]]], Optional): Configuration of how to link from source_class to target_class. If None then
                the default linkage in the config file is used. Defaults to None.

        Returns:
            Any: The first linked value in the target class and slot. If no linked value is found then None is returned.
        """
        row = self.get_first_linked_row(source_class, source_index, target_class, linkage_path)
        if row is None:
            return None
        if self.is_id_generated_slot(target_class, target_slot) and pd.isna(row[target_slot]):
            return self.calculate_id(target_class, target_slot, row.name)
        return row[target_slot]
    
    def finalize_value(self, v: Any) -> Any:
        """Finalize a value retrieved from a DataFrame or calculated with ID generation code. This should
        be called on any value calculated based on ID generated code before it gets used in a final ID in
        the output DataFrame.
        
        We will do some processing such as replacing blank values with EMPTY_VALUE.

        Args:
            v (Any): The value to finalize.

        Returns:
            Any: The finalized value.
        """
        if pd.isna(v) or v == "":
            return EMPTY_VALUE
        if isinstance(v, float):
            if int(v) == v:
                return int(v)
        return v
    
    def calculate_id(self, cls: str, slot: str, row_index: int) -> Any:
        """Calculate the ID for the slot in the class at the specified row index. The ID is
        calculated based on the ID generation code for the class/slot combination, and is found
        in the ID code config file.

        Args:
            cls (str): The class that the slot belongs to.
            slot (str): The slot to calculate the ID for.
            row_index (int): The row index in the class's DataFrame that we calculate the slot for.

        Returns:
            Any: The calculated ID.
        """
        if cls not in self.data:
            return None

        code = self.get_code(cls, slot)
        
        if pd.isna(code) or not code:
            return None
                
        old_class = self.current_class
        old_row_index = self.current_row_index
        v = self.interpreter(code)
        v = self.finalize_value(v)
        
        # @TODO: Test this!!
        filt = self.data[cls][f"{ORIG_ID_PREFIX}{slot}"] == self.data[cls][f"{ORIG_ID_PREFIX}{slot}"].iloc[row_index]
        self.data[cls].loc[filt, slot] = v
        # self.data[cls].loc[row_index, slot] = v
        
        self.current_class = old_class
        self.current_row_index = old_row_index
        return v
                    
    def get_rows_equal(self, cls: str, slot: str, match_value: Any) -> pd.DataFrame:
        """Get the rows in class cls where slot is equal to match_value.

        Args:
            cls (str): The class to get the rows from.
            slot (str): The slot in the class to use for matching.
            match_value (Any): The value(s) to match. If a list or tuple then we match any of the values in the list. If not a list
                then we only match the single value.

        Returns:
            pd.DataFrame: All rows in the class cls, where the value in the slot is equal to the value specified by match_value.
                None if no matching rows are found.
        """
        data = self.data[cls]
        if not isinstance(match_value, (list, tuple)):
            match_value = [match_value]
        if len([v for v in match_value if pd.isna(v)]):
            na_filt = pd.isna(data[slot])
        else:
            na_filt = False
        rows = data[data[slot].isin(match_value) | na_filt]
        return rows if len(rows) else None
    
    def speed_test(self):
        tic = datetime.now()
        cls = "protocolSteps"
        for idx in tqdm(self.data[cls].index):
            row = self.get_rows_at_index(cls, idx)
        print("Finished speed test:", datetime.now() - tic)
    
    def get_rows_at_index(self, cls: str, index: Union[int, List[int]]) -> pd.DataFrame:
        """Get the row(s) in the class at the specified indices.

        Args:
            cls (str): The class to get the rows from.
            index (Union[int, List[int]]): A single index or list of indices to retrieve the
                rows of.

        Returns:
            pd.DataFrame: The retrieved rows.
        """
        if isinstance(index, int):
            index = [index]
        return self.data[cls].loc[index]
    
    def get_linked_rows(self, source_class: str, source_index: Union[int, List[int]], target_class: str, linkage_path: Optional[Union[Dict, List[Dict]]]=None) -> pd.DataFrame:
        """Get the rows in target_class, that are linked to the row(s) at index source_index in source_class. Use the linkage path to determine
        the linking steps required to go from source_class to target_class. If linkage_path is None then we use the
        linkage path found in the config file (under the "class_linkages" key). Typically, rows in different classes
        are linked by foreign keys and primary keys.

        Args:
            source_class (str): The source class that we are linking from.
            source_index (Union[int, List[int]]): The row index(es) in the source class to link from.
            target_class (str): The target class to get the linked rows from.
            linkage_path (Optional[Union[Dict, List[Dict]]], Optional): Configuration of how to link from source_class to target_class. If None then
                the default linkage in the config file is used. Defaults to None.

        Returns:
            pd.DataFrame: The linked rows, or None if no linkage could be performed.
        """
        if source_class not in self.data or target_class not in self.data:
            return None

        # If the source_class and target_class are the same, then we just return the source row
        # (in class source_class and row source_index)
        if source_class == target_class:
            return self.get_rows_at_index(source_class, source_index)
        
        # Load the linkage path that goes from the source_class to target_class, if it was not specified.
        if linkage_path is None:
            linkage_path = self.get_default_linkage_path(source_class, target_class)
        
        # If no linkage path is available, then return None
        if linkage_path is None:
            # raise ValueError(f"No linkage path available to link from class '{source_class}' to class '{target_class}'")
            return None
                
        if not isinstance(linkage_path, (list, tuple)):
            linkage_path = [linkage_path]
        
        # Loop through the linkage path to link from the source class (and source index) to the
        # target class. We retrieve all rows in the target class that are linked to rows in the
        # source class.
        cur_class = source_class
        rows = self.get_rows_at_index(source_class, source_index)
        if rows is None:
            raise ValueError(f"No row(s) at index {source_index} in class '{source_class}'")
        for linkage in linkage_path:
            linkage_source_class = linkage[LinkageKeys.SOURCE_CLASS]
            linkage_source_slot = linkage[LinkageKeys.SOURCE_SLOT]
            linkage_target_class = linkage[LinkageKeys.TARGET_CLASS]
            linkage_target_slot = linkage[LinkageKeys.TARGET_SLOT]
            
            if cur_class != linkage_source_class:
                raise ValueError(f"source_class ('{linkage_source_class}') does not match current class ('{cur_class}') in linkage path from '{source_class}' to '{target_class}'.")
            
            values = list(rows[linkage_source_slot].unique())
            rows = self.get_rows_equal(linkage_target_class, linkage_target_slot, values)
            if rows is None:
                # logger.info(f"No linked rows, from class '{source_class}' to '{target_class}' (with source index '{source_index}')")
                return None
            
            cur_class = linkage_target_class
            
        return rows
        
    def get_default_linkage_path(self, source_class: str, target_class: str) -> Optional[Union[Dict, List[Dict]]]:
        """Get the default class linkage, that specifies the steps required to link a row in source_class to
        row(s) in target_class. The default linkage is the one specified in the config file under the
        "class_linkages" key.

        Args:
            source_class (str): The source class to link from.
            target_class (str): The target class to link to.

        Returns:
            Optional[Union[Dict, List[Dict]]]: The list of linkage steps (or optionally a dictionary if the linkage path has a
            single step) to go from the source class to target class. The dictionaries are of the form:
                    {
                        source_class: "class1",
                        source_slot: "slot1",
                        target_class: "class2",
                        target_slot: "slot2",
                    }
                In the above example, to go link rows in "class1" to rows in "class2", we extract all rows from "class2"
                where "slot2" is equal to the value found in the source row in "slot1". In some cases, we may need to link
                through multiple classes to get from the source class to the target class. This is specified by having multiple
                dictionaries in the returned list. Returns None if no linkage path from source_class to target_class is available.
        """
        if source_class not in self.config["class_linkages"]:
            return None
        linkage = self.config["class_linkages"][source_class]
        return linkage.get(target_class, None)
                    
    def save_all(self, output_dir: str):
        """Save all DataFrames to disk.

        Args:
            output_dir (str): Directory to save DataFrames to.
        """
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
        for cls, df in self.data.items():
            output_file = os.path.join(output_dir, f"{cls}_ids.csv")
            save_data_frame(df, output_file, index=False)

if __name__ == "__main__":
    if "get_ipython" in globals():
        class opts:
            data_dir = "../../gen/nwss_reporting_to_v2/mapped_data"
            output_dir = "../../gen/nwss_reporting_to_v2/mapped_data_ids"
            config_file = "../../data/odm_v2/odm_v2_id_config.yaml"
            id_code_file = "../../data/odm_v2/odm_v2_id_code.xlsx"
            id_code_sheet = "id_code"
    else:
        args = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
        args.add_argument("--data_dir", type=str, help="Location of all data files to add the IDs to. The file name (without extension) should be the class name. All CSV, TSV, TXT, YAML, and YML files are loaded.", required=True)
        args.add_argument("--output_dir", type=str, help="Directory to save the final data to, in which all IDs have been generated.", required=True)
        args.add_argument("--config_file", type=str, help="The YAML config file.", required=True)
        args.add_argument("--id_code_file", type=str, help="The XLSX, CSV, TSV, TXT, YAML, or YML configuration file that contains the ID generation code. If an XLSX file then the sheet named id_code_sheet is loaded.", required=True)
        args.add_argument("--id_code_sheet", type=str, help="If id_code_file is an Excel file, then load the code from the sheet with this name.", default=None, required=False)
        opts = args.parse_args()
        
    gen = IDGenerator(opts.data_dir, opts.config_file, opts.id_code_file, opts.id_code_sheet)
    gen.make_all_ids()
    gen.save_all(opts.output_dir)